unom/accounts/urls.py
from django.conf.urls import url, include
from .views import UserRegistrationView,MyActivationView

from .forms import UserRegistrationForm

urlpatterns = [
    url(r'^register/$', UserRegistrationView.as_view(form_class=UserRegistrationForm),
        name='registration_register',),
    url(r'^activate/accounts/(?P<activation_key>\w+)/$', MyActivationView.as_view(),
        name='activation',),

    url(r'^', include('registration.backends.default.urls')),
]

unom/custom/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^emaillogin/$', views.email_login_view, name='email_login_view'),

]

unom/home/urls.py
from django.conf.urls import url, include

from accounts.views import UserRegistrationView
from accounts.forms import UserRegistrationForm


urlpatterns = [
    url(r'^$', UserRegistrationView.as_view(), name='index'),
]

unom/todolist/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^$', views.todo, name='todo_index'),

    url(r'^posttodo/$', views.post_todo, name='post_todo'),
    url(r'^gettodo/$', views.todo_all, name='todo_all'),


    # api
    # url(r'^api/v1/todos/$',views.todo_all ,name= 'todo_all'),


]

unom/unom/urls.py
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin

from startup import startup


urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', include('home.urls'), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^custom/', include('custom.urls', namespace='custom')),
    url(r'^todolist/', include('todolist.urls',namespace='todolist')),
    url(r'^zendesk/', include('zendesk.urls',namespace='zendesk')),
    url(r'^', include('registration.backends.default.urls')),


]


#*** ON FIRST RUN OF THE SERVER UNCOMMENT THE FOLLOWING STARTUP FUCNTION TO START INTIALISATION OF CELERY django_celery_beat SCHEDUALED TASKS> WHEN CREATED RECOMMENT LINES
# MUST BE A BETTER SOULTIION BUT FOR NOW THIS THE DIRTY FIX

# startup()

unom/templates/base.html
{% load staticfiles %}


<html lang="en">
<head>
  <meta charset="utf-8">

  <title></title>

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->

{% include "common_javascript.html" %}
{% include "common_css.html" %}
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</body>
</html>

unom/templates/common_css.html
{% load staticfiles %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

unom/templates/common_javascript.html
 <!-- Javascript which is used on all pages/ site wide -->

{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

unom/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<!-- <h1>To Do List</h1> -->


{% if not request.user.is_authenticated %}
<div class="container">
<div >

  <h1>Register</h1>
  <form lass="form-horizontal  col-md-6 pull-right" method="post" action="">
    {% csrf_token %}
    {{ form.as_table }}

     <input class='btn btn-block btn-primary' type="submit" value="Join" />
  </form>


</div>
</div>
{% endif %}

{% endblock %}


{% block content %}



{% if request.user.is_authenticated %}
<h1>You are logged in!</h1>
{% endif %}


</div>

<!-- <script type="text/javascript" src="{% static 'js/main.js' %}"></script> -->



{% endblock %}

unom/templates/navbar.html
{% load staticfiles %}

<!-- This markup was taken from an older project of mine and is not new code, I do not know the full details of all the bootstrap classes here -->

 <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
                </button>
        <a class="navbar-brand" href="/">HOME</a>
        <a class="navbar-brand" href="{% url "todolist:todo_index" %}">Tasks</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">


        </ul>

        <ul class="nav navbar-nav navbar-right">
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'auth_logout' %}">{{ request.user }} - Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:registration_register' %}">Register</a></li>
        {% endif %}
      </ul>

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
        <form class='navbar-form navbar-right' method='POST' action='{% url "custom:email_login_view" %}'>{% csrf_token %}
          <div class='form-group'>
              <input type='text' class='form-control' name='email' placeholder='email' />
          </div>
          <div class='form-group'>
              <input type='password' class='form-control' name='password' placeholder='Password' />
          </div>
          <button type='submit' class='btn btn-default'>Login</button>
      </form>
      {% endif %}


      </div><!--/.nav-collapse -->
    </div>
  </nav>

unom/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block content %}
<div class="container">
<div class="col-md-6 col-md-offset-3">

  <h1>Register</h1>
  <form lass="form-horizontal  col-md-6 pull-right" method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}

     <input class='btn btn-block btn-primary' type="submit" value="Join" />
  </form>


</div>
</div> 
 {% endblock %}